# add stages here 
stages:
  prepare_data:
    cmd: python src/stage_01_prepare.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_01_prepare.py
      - nlpdata/data.xml
      - src/utils/common.py
      - configs/config.yaml
    params:
     - prepare.seed
     - prepare.split
    outs:
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv

  featurize_data:
    cmd: python src/stage_02_featurization.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_02_featurization.py
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv
      - src/utils/common.py
      - src/utils/featurize.py
      - configs/config.yaml
    params:
     - featurize.max_features
     - featurize.ngrams
    outs:
      - artifacts/feature/train.pkl
      - artifacts/feature/test.pkl

  training:
    cmd: python src/stage_03_train.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_03_train.py
      - artifacts/feature/train.pkl
      - src/utils/common.py
      - configs/config.yaml
    params:
     - train.seed
     - train.n_est
     - train.min_split
    outs:
      - artifacts/model/model.pkl

  evaluate:
    cmd: python src/stage_04_evaluate.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_04_evaluate.py
      - artifacts/feature/test.pkl
      - src/utils/common.py
      - artifacts/model/model.pkl
      - configs/config.yaml
    metrics:
      - scores.json:
          cache: false
    plots:
      - prc.json:
          cache: false
          x: recall
          y: precision
      - roc.json:
          cache: false
          x: fpr
          y: tpr

  
  run_plots_command:
    cmd: dvc plots diff
      
