# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv
  FEATURIZED_DATA: feature
  FEATURIZED_OUT_TRAIN: train.pkl
  FEATURIZED_OUT_TEST: test.pkl
  MODEL_DIR: model
  MODEL_NAME: model.pkl

metrics:
  SCORES: scores.json

plots:
  PRC: prc.json
  ROC: roc.json
     
source_download_dirs:
  data_dir: nlpdata
  data_file: data.xml